# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addFace', '0007_auto_20170331_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='encode',
            field=models.CharField(max_length=2000),
        ),
    ]
