# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addFace', '0008_auto_20170331_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='encode',
            field=models.FileField(upload_to=''),
        ),
    ]
