# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addFace', '0009_auto_20170331_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='encode',
            new_name='photo',
        ),
    ]
