# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addFace', '0010_auto_20170331_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
