# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addFace', '0011_auto_20170331_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
