# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addFace', '0012_auto_20170402_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='Known_people'),
        ),
    ]
