# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchindb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
