# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchindb', '0002_auto_20170331_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='photo',
            field=models.ImageField(upload_to='unkown_people'),
        ),
    ]
